name: Generate Snake

on:
  schedule:
    - cron: '30 5,17 * * *'  # Ensure cron schedule is correct
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3  # Updated to the latest version

    - name: Generate the snake contribution GIF and SVG
      uses: Platane/snk@v2.0.0  # Updated to a stable version
      id: snake-gif
      with:
        github_user_name: Aleeze123
        gif_out_path: dist/github-contribution-grid-snake.gif
        svg_out_path: dist/github-contribution-grid-snake.svg

    - name: Push changes to output branch
      uses: ad-m/github-push-action@v0.6.0  # Consider specifying a stable version
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: output
        force: true

    - name: Deploy to GitHub Pages
      uses: crazy-max/ghaction-github-pages@v2.1.3
      with:
        target_branch: output
        build_dir: dist
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
